// src/themes/theme.css.js
import { createThemeContract } from '@vanilla-extract/css';

const defaultColors = {
    1: '',
    2: '',
    3: '',
    4: '',
    5: '',
    6: '',
    7: '',
    8: '',
    9: '',
    10: '',
    11: '',
    12: '',
};

const defaultPalette = {
    amber: { ...defaultColors },
    amberA: { ...defaultColors },
    blue: { ...defaultColors },
    blueA: { ...defaultColors },
    bronze: { ...defaultColors },
    bronzeA: { ...defaultColors },
    brown: { ...defaultColors },
    brownA: { ...defaultColors },
    crimson: { ...defaultColors },
    crimsonA: { ...defaultColors },
    cyan: { ...defaultColors },
    cyanA: { ...defaultColors },
    gold: { ...defaultColors },
    goldA: { ...defaultColors },
    grass: { ...defaultColors },
    grassA: { ...defaultColors },
    gray: { ...defaultColors },
    grayA: { ...defaultColors },
    green: { ...defaultColors },
    greenA: { ...defaultColors },
    indigo: { ...defaultColors },
    indigoA: { ...defaultColors },
    iris: { ...defaultColors },
    irisA: { ...defaultColors },
    jade: { ...defaultColors },
    jadeA: { ...defaultColors },
    lime: { ...defaultColors },
    limeA: { ...defaultColors },
    mauve: { ...defaultColors },
    mauveA: { ...defaultColors },
    mint: { ...defaultColors },
    mintA: { ...defaultColors },
    olive: { ...defaultColors },
    oliveA: { ...defaultColors },
    orange: { ...defaultColors },
    orangeA: { ...defaultColors },
    pink: { ...defaultColors },
    pinkA: { ...defaultColors },
    plum: { ...defaultColors },
    plumA: { ...defaultColors },
    purple: { ...defaultColors },
    purpleA: { ...defaultColors },
    red: { ...defaultColors },
    redA: { ...defaultColors },
    ruby: { ...defaultColors },
    rubyA: { ...defaultColors },
    sage: { ...defaultColors },
    sageA: { ...defaultColors },
    sand: { ...defaultColors },
    sandA: { ...defaultColors },
    sky: { ...defaultColors },
    skyA: { ...defaultColors },
    slate: { ...defaultColors },
    slateA: { ...defaultColors },
    teal: { ...defaultColors },
    tealA: { ...defaultColors },
    tomato: { ...defaultColors },
    tomatoA: { ...defaultColors },
    violet: { ...defaultColors },
    violetA: { ...defaultColors },
    yellow: { ...defaultColors },
    yellowA: { ...defaultColors },
};

export const theme = createThemeContract({
    colors: {
        solid: {
            alert: { ...defaultColors },
            base: { ...defaultColors },
            primary: { ...defaultColors },
            success: { ...defaultColors },
            warning: { ...defaultColors },
        },
        alpha: {
            alert: { ...defaultColors },
            base: { ...defaultColors },
            primary: { ...defaultColors },
            success: { ...defaultColors },
            warning: { ...defaultColors },
        },
    },
    palette: { ...defaultPalette },
});

/*

*/
